// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {doctor} from '../models';
import {main} from '../models';
import {settings} from '../models';

export function GetDoctorResults():Promise<doctor.DoctorReport>;

export function ImportImages():Promise<main.ImportResult>;

export function LoadApplicationSettings():Promise<settings.AppSettings>;

export function ResetAppSettings():Promise<settings.AppSettings>;
