// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {doctor} from '../models';
import {main} from '../models';
import {settings} from '../models';
import {workflow} from '../models';
import {processing} from '../models';

export function GetDoctorResults():Promise<doctor.DoctorReport>;

export function ImportImages():Promise<main.ImportResult>;

export function LoadApplicationSettings():Promise<settings.AppSettings>;

export function ResetAppSettings():Promise<settings.AppSettings>;

export function SelectARWDirectory():Promise<string>;

export function ShowPathInFinder(arg1:string):Promise<boolean>;

export function StartProcessingWorkflow(arg1:workflow.Workflow,arg2:processing.ImageBatch):Promise<void>;

export function UpdateARWSetting(arg1:boolean):Promise<void>;

export function UpdateARWTempFilePath(arg1:string):Promise<void>;

export function UpdateSettings(arg1:settings.AppSettings):Promise<void>;

export function UpdateTimelapseSetting(arg1:boolean):Promise<void>;
