// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDoctorResults() {
  return window['go']['main']['App']['GetDoctorResults']();
}

export function ImportImages() {
  return window['go']['main']['App']['ImportImages']();
}

export function LoadApplicationSettings() {
  return window['go']['main']['App']['LoadApplicationSettings']();
}

export function ResetAppSettings() {
  return window['go']['main']['App']['ResetAppSettings']();
}

export function StartProcessingWorkflow(arg1, arg2) {
  return window['go']['main']['App']['StartProcessingWorkflow'](arg1, arg2);
}

export function UpdateARWSetting(arg1) {
  return window['go']['main']['App']['UpdateARWSetting'](arg1);
}

export function UpdateTimelapseSetting(arg1) {
  return window['go']['main']['App']['UpdateTimelapseSetting'](arg1);
}
